### ISSUE TITLE
同时有微信和google账号关联的时候，貌似无法更新Phonetic name

### ISSUE THREAD

**Issue by iciness** [ranmocy/MonkeyTree#2]
Nexus 6 android 7.0

**Comment by ranmocy** [comment]
请问如何将微信集成到通讯录？我尝试从 Contacts app 中添加微信账户，并打开微信的通讯录权限，但是 Contacts 里面仍然看不到微信的信息。但是能看到 Telegram 的联系人信息。需要在微信里面设置什么么？

**Comment by iciness** [comment]
不用在微信里做什么，微信会自动在系统账户里添加一个微信账号，手动也能添加

**Comment by ranmocy** [comment]
账号是已经添加了的，但是 Contacts app 里还是看不到微信信息。请提供一下 Android、Contacts、微信的版本号。

**Comment by iciness** [comment]
Nexus 6 Android 7.0
微信6.3.31
Contacts 1.5.16

**Comment by iciness** [comment]
![wechatimg26](https://cloud.githubusercontent.com/assets/4505686/21079111/3caf824a-bfc2-11e6-9600-6dd44f7091a9.jpeg)
![wechatimg27](https://cloud.githubusercontent.com/assets/4505686/21079112/3cb16272-bfc2-11e6-9801-21fa83759646.jpeg)
![wechatimg28](https://cloud.githubusercontent.com/assets/4505686/21079113/3cc31ff8-bfc2-11e6-9496-dc87ee894738.png)
![wechatimg29](https://cloud.githubusercontent.com/assets/4505686/21079114/3cd19b6e-bfc2-11e6-8733-789088e89e7e.jpeg)

**Comment by ranmocy** [comment]
Nexus 5X Android 7.0
微信 6.3.31
Contacts 1.5.16
Monkey Tree 1.1
我测试是可以正常更新拼音。请更新一下 Monkey Tree，用新添加的按钮清除 Phonetic 信息，再添加试一下。
![photo_2016-12-11_21-04-46](https://cloud.githubusercontent.com/assets/601767/21088714/b43d9dc8-bfe6-11e6-8589-515b13a4f6b4.jpg)

但是
Pixel Android 7.1.1
Contacts 1.6.15
微信 6.3.31
就彻底看不到信息。

**Comment by iciness** [comment]
我用老版后来是先删掉微信这个账号后更新就没问题

**Comment by ranmocy** [comment]
奇怪的问题。既然能 workaround，这个 Issue 先关闭。
