### ISSUE TITLE
多音字问题

### ISSUE THREAD

**Issue by zyh941** [ranmocy/MonkeyTree#3]
覃 字，现在app总是把它改成 tan2，然而应该是 qin2,作者能否更新一下规则？

**Comment by ranmocy** [comment]
这个问题略麻烦，根据Wikipedia，在不同的地区的人会用不同的发音：
https://zh.wikipedia.org/zh-cn/%E8%A6%83%E5%A7%93

> 覃姓是一个有多种读音的姓氏
> 
> 读为tán，主要分布在黄河流域的北方各省和关陇地区。
> 读为xún，主要生活在四川一带的覃姓人仍把自己的姓氏读为xún。
> 读为qín，主要生活在今广西一带的覃姓人。

现在如果数据库里有发音信息，app在更新的时候会跳过，这样用户手动修正的信息不会被再次覆盖。
如果用户希望强制覆盖，可以手动清除发音信息（app里可以一键清除全部发音信息），然后在点击更新信息按钮。

暂时没有更好的简单设计
